SERVER_HOST = 'localhost'
SERVER_PORT = 12337

#CLIENT_HOST = '10.42.0.1'
CLIENT_HOST = 'localhost'
CLIENT_PORT = 12337

BUFFER_SIZE = 4096

CHECK_REQUEST_INTERVAL = False
MIN_REQUEST_INTERVAL = 0.1 #s

CHECK_LEVENSHTEIN = True
ACTIONS_PER_SEQUENCE = 4
SEQUENCES_FOR_CHECK = 2
MIN_AVG_SIMILARITY = 3.0
